/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Bookmark } from "./types/bookmark";
export namespace Components {
    interface AppAddBookmarkForm {
    }
    interface AppBookmark {
        "bookmark": Bookmark;
    }
    interface AppBookmarks {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAddBookmarkFormElement extends Components.AppAddBookmarkForm, HTMLStencilElement {
    }
    var HTMLAppAddBookmarkFormElement: {
        prototype: HTMLAppAddBookmarkFormElement;
        new (): HTMLAppAddBookmarkFormElement;
    };
    interface HTMLAppBookmarkElement extends Components.AppBookmark, HTMLStencilElement {
    }
    var HTMLAppBookmarkElement: {
        prototype: HTMLAppBookmarkElement;
        new (): HTMLAppBookmarkElement;
    };
    interface HTMLAppBookmarksElement extends Components.AppBookmarks, HTMLStencilElement {
    }
    var HTMLAppBookmarksElement: {
        prototype: HTMLAppBookmarksElement;
        new (): HTMLAppBookmarksElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-add-bookmark-form": HTMLAppAddBookmarkFormElement;
        "app-bookmark": HTMLAppBookmarkElement;
        "app-bookmarks": HTMLAppBookmarksElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAddBookmarkForm {
    }
    interface AppBookmark {
        "bookmark"?: Bookmark;
    }
    interface AppBookmarks {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-add-bookmark-form": AppAddBookmarkForm;
        "app-bookmark": AppBookmark;
        "app-bookmarks": AppBookmarks;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-add-bookmark-form": LocalJSX.AppAddBookmarkForm & JSXBase.HTMLAttributes<HTMLAppAddBookmarkFormElement>;
            "app-bookmark": LocalJSX.AppBookmark & JSXBase.HTMLAttributes<HTMLAppBookmarkElement>;
            "app-bookmarks": LocalJSX.AppBookmarks & JSXBase.HTMLAttributes<HTMLAppBookmarksElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
